/**
 * Open-source packages InTempo is built on.
 *
 * Generated by `scripts/generate-licences.mjs` from the installed tree — do
 * not edit by hand, and re-run it after changing dependencies. Direct
 * dependencies only: the transitive tree is hundreds of packages and nobody
 * reads it.
 */
export interface Licence {
  name: string;
  version: string;
  licence: string;
}

export const LICENCES: Licence[] = [
  { name: '@expo-google-fonts/inter', version: '0.4.2', licence: 'MIT AND OFL-1.1' },
  { name: '@expo-google-fonts/newsreader', version: '0.4.1', licence: 'MIT AND OFL-1.1' },
  { name: '@expo/metro-runtime', version: '57.0.10', licence: 'MIT' },
  { name: '@react-native-async-storage/async-storage', version: '3.1.1', licence: 'MIT' },
  { name: '@react-navigation/bottom-tabs', version: '7.18.16', licence: 'MIT' },
  { name: '@react-navigation/native', version: '7.3.16', licence: 'MIT' },
  { name: '@react-navigation/native-stack', version: '7.18.8', licence: 'MIT' },
  { name: '@supabase/supabase-js', version: '2.112.3', licence: 'MIT' },
  { name: '@tanstack/react-query', version: '5.101.4', licence: 'MIT' },
  { name: '@types/react', version: '19.2.18', licence: 'MIT' },
  { name: 'expo', version: '57.0.13', licence: 'MIT' },
  { name: 'expo-font', version: '57.0.1', licence: 'MIT' },
  { name: 'expo-haptics', version: '57.0.1', licence: 'MIT' },
  { name: 'expo-image', version: '57.0.3', licence: 'MIT' },
  { name: 'expo-status-bar', version: '57.0.1', licence: 'MIT' },
  { name: 'lucide-react-native', version: '1.31.0', licence: 'ISC' },
  { name: 'react', version: '19.2.3', licence: 'MIT' },
  { name: 'react-dom', version: '19.2.3', licence: 'MIT' },
  { name: 'react-native', version: '0.86.2', licence: 'MIT' },
  { name: 'react-native-safe-area-context', version: '5.9.0', licence: 'MIT' },
  { name: 'react-native-screens', version: '4.27.0', licence: 'MIT' },
  { name: 'react-native-svg', version: '15.15.5', licence: 'MIT' },
  { name: 'react-native-url-polyfill', version: '4.0.0', licence: 'MIT' },
  { name: 'react-native-web', version: '0.21.2', licence: 'MIT' },
  { name: 'typescript', version: '6.0.3', licence: 'Apache-2.0' },
];
