// Generated by scripts/prepare-instrument-samples.mjs. See assets/instruments/NOTICE.md.
import type { Instrument } from '../../data/types';
export const SAMPLE_ASSETS: Record<
  Instrument,
  { midi: number; tune: number; asset: number }[]
> = {
  violin: [
    {
      midi: 57,
      tune: 0,
      asset: require('../../../assets/instruments/violin-57.wav'),
    },
    {
      midi: 64,
      tune: 0,
      asset: require('../../../assets/instruments/violin-64.wav'),
    },
    {
      midi: 69,
      tune: 0,
      asset: require('../../../assets/instruments/violin-69.wav'),
    },
    {
      midi: 76,
      tune: 0,
      asset: require('../../../assets/instruments/violin-76.wav'),
    },
    {
      midi: 81,
      tune: 0,
      asset: require('../../../assets/instruments/violin-81.wav'),
    },
    {
      midi: 88,
      tune: 0,
      asset: require('../../../assets/instruments/violin-88.wav'),
    },
  ],
  viola: [
    {
      midi: 48,
      tune: 0,
      asset: require('../../../assets/instruments/viola-48.wav'),
    },
    {
      midi: 55,
      tune: 0,
      asset: require('../../../assets/instruments/viola-55.wav'),
    },
    {
      midi: 62,
      tune: 0,
      asset: require('../../../assets/instruments/viola-62.wav'),
    },
    {
      midi: 69,
      tune: 0,
      asset: require('../../../assets/instruments/viola-69.wav'),
    },
    {
      midi: 76,
      tune: 0,
      asset: require('../../../assets/instruments/viola-76.wav'),
    },
  ],
  cello: [
    {
      midi: 36,
      tune: 0,
      asset: require('../../../assets/instruments/cello-36.wav'),
    },
    {
      midi: 43,
      tune: 0,
      asset: require('../../../assets/instruments/cello-43.wav'),
    },
    {
      midi: 50,
      tune: 0,
      asset: require('../../../assets/instruments/cello-50.wav'),
    },
    {
      midi: 57,
      tune: 0,
      asset: require('../../../assets/instruments/cello-57.wav'),
    },
    {
      midi: 64,
      tune: 0,
      asset: require('../../../assets/instruments/cello-64.wav'),
    },
  ],
  double_bass: [
    {
      midi: 28,
      tune: 0,
      asset: require('../../../assets/instruments/double_bass-28.wav'),
    },
    {
      midi: 36,
      tune: 0,
      asset: require('../../../assets/instruments/double_bass-36.wav'),
    },
    {
      midi: 44,
      tune: 0,
      asset: require('../../../assets/instruments/double_bass-44.wav'),
    },
    {
      midi: 52,
      tune: 0,
      asset: require('../../../assets/instruments/double_bass-52.wav'),
    },
  ],
};
