/**
 * The pieces a string player at this app's level is likely to be adding —
 * what the title field offers as you type (`autofill.ts`).
 *
 * **Asked for by the owner (2026-09-26)**: *"an auto fill feature for pieces
 * and composer where when you type a letter it gives you a recommendation in
 * the typing bar kind of like Google Docs"*, with the musician's own library
 * searched first and this list after it.
 *
 * **Order is the ranking.** One letter is enough to be offered something, so
 * the first title in this list that starts with what was typed is the one
 * shown. The list therefore runs roughly from what is most often on a stand —
 * method-book pieces, the student concertos, the études — to the concert
 * repertoire and then orchestral parts.
 *
 * **A composer who is in `composers.ts` is written exactly as it writes them**
 * ("J. S. Bach", "W. A. Mozart"), because accepting a title fills in an empty
 * composer field, and a library groups and draws covers by that spelling. A
 * test holds every entry to it. Anyone else is written the usual way; the
 * field is free text and so is this.
 *
 * `composer` is null for a traditional tune, where filling the field would
 * put a name there that nobody wrote.
 *
 * Nothing here is a constraint: a title not on the list is typed and kept,
 * exactly as it always was.
 */

export interface Work {
  title: string;
  composer: string | null;
}

const w = (title: string, composer: string | null): Work => ({ title, composer });

export const REPERTOIRE: Work[] = [
  // Method-book pieces (Suzuki and the like), in roughly the order learned.
  w('Twinkle, Twinkle, Little Star Variations', 'Shinichi Suzuki'),
  w('Lightly Row', null),
  w('Song of the Wind', null),
  w('Go Tell Aunt Rhody', null),
  w('O Come, Little Children', null),
  w('May Song', null),
  w('Long, Long Ago', 'Thomas Haynes Bayly'),
  w('Allegro', 'Shinichi Suzuki'),
  w('Perpetual Motion', 'Shinichi Suzuki'),
  w('Allegretto', 'Shinichi Suzuki'),
  w('Andantino', 'Shinichi Suzuki'),
  w('Minuet 1', 'J. S. Bach'),
  w('Minuet 2', 'J. S. Bach'),
  w('Minuet 3', 'J. S. Bach'),
  w('The Happy Farmer', 'Robert Schumann'),
  w('Gavotte', 'François-Joseph Gossec'),
  w('Chorus from Judas Maccabaeus', 'George Frideric Handel'),
  w('Musette', 'J. S. Bach'),
  w("Hunters' Chorus", 'Carl Maria von Weber'),
  w('Waltz', 'Johannes Brahms'),
  w('Bourrée', 'George Frideric Handel'),
  w('The Two Grenadiers', 'Robert Schumann'),
  w("Theme from Witches' Dance", 'Niccolò Paganini'),
  w('Gavotte from Mignon', 'Ambroise Thomas'),
  w('Minuet in G, WoO 10 No. 2', 'Ludwig van Beethoven'),
  w('Minuet', 'Luigi Boccherini'),
  w('Gavotte in G minor', 'J. S. Bach'),
  w('Humoresque, Op. 101 No. 7', 'Antonín Dvořák'),
  w('Gavotte in D major', 'J. S. Bach'),
  w('Country Dance', 'Carl Maria von Weber'),
  w('German Dance', 'Carl Ditters von Dittersdorf'),
  w('Gigue', 'Francesco Maria Veracini'),
  w('Allegro', 'Joseph-Hector Fiocco'),

  // Student concertos.
  w('Student Concerto No. 2 in G major, Op. 13', 'Friedrich Seitz'),
  w('Student Concerto No. 3 in G minor, Op. 12', 'Friedrich Seitz'),
  w('Student Concerto No. 5 in D major, Op. 22', 'Friedrich Seitz'),
  w('Concertino in G major, Op. 11', 'Ferdinand Küchler'),
  w('Concertino in D major, Op. 15', 'Ferdinand Küchler'),
  w('Concerto in B minor, Op. 35', 'Oskar Rieding'),
  w('Concerto No. 1 in A minor', 'Jean-Baptiste Accolay'),
  w('Concerto in A minor, RV 356', 'Antonio Vivaldi'),
  w('Concerto in G minor, RV 317', 'Antonio Vivaldi'),
  w('Concerto for Two Violins in A minor, RV 522', 'Antonio Vivaldi'),
  w('Concerto for Two Violins in D minor, BWV 1043', 'J. S. Bach'),

  // Études and methods.
  w('60 Studies, Op. 45', 'Franz Wohlfahrt'),
  w('36 Studies, Op. 20', 'Heinrich Ernst Kayser'),
  w('42 Studies', 'Rodolphe Kreutzer'),
  w('Études spéciales, Op. 36', 'Jacques Féréol Mazas'),
  w('24 Caprices', 'Pierre Rode'),
  w('24 Études and Caprices, Op. 35', 'Jakob Dont'),
  w('School of Violin Technique, Op. 1', 'Otakar Ševčík'),
  w('Scale System', 'Carl Flesch'),
  w('24 Caprices, Op. 1', 'Niccolò Paganini'),
  w('Caprice No. 24 in A minor', 'Niccolò Paganini'),
  w('41 Caprices, Op. 22', 'Bartolomeo Campagnoli'),
  w('113 Studies', 'Friedrich Dotzauer'),
  w('40 Melodic and Progressive Études, Op. 31', 'Sebastian Lee'),
  w('170 Foundation Studies', 'Alwin Schroeder'),
  w('21 Études', 'Jean-Louis Duport'),
  w('High School of Cello Playing, Op. 73', 'David Popper'),
  w('New Method for the Double Bass', 'Franz Simandl'),
  w('30 Études for the String Bass', 'Franz Simandl'),
  w('Complete Method for the Double Bass', 'Édouard Nanny'),

  // Unaccompanied Bach.
  w('Cello Suite No. 1 in G major, BWV 1007', 'J. S. Bach'),
  w('Cello Suite No. 2 in D minor, BWV 1008', 'J. S. Bach'),
  w('Cello Suite No. 3 in C major, BWV 1009', 'J. S. Bach'),
  w('Cello Suite No. 4 in E-flat major, BWV 1010', 'J. S. Bach'),
  w('Cello Suite No. 5 in C minor, BWV 1011', 'J. S. Bach'),
  w('Cello Suite No. 6 in D major, BWV 1012', 'J. S. Bach'),
  w('Sonata No. 1 in G minor, BWV 1001', 'J. S. Bach'),
  w('Partita No. 1 in B minor, BWV 1002', 'J. S. Bach'),
  w('Sonata No. 2 in A minor, BWV 1003', 'J. S. Bach'),
  w('Partita No. 2 in D minor, BWV 1004', 'J. S. Bach'),
  w('Chaconne from Partita No. 2 in D minor', 'J. S. Bach'),
  w('Sonata No. 3 in C major, BWV 1005', 'J. S. Bach'),
  w('Partita No. 3 in E major, BWV 1006', 'J. S. Bach'),

  // Violin concertos.
  w('Violin Concerto in A minor, BWV 1041', 'J. S. Bach'),
  w('Violin Concerto in E major, BWV 1042', 'J. S. Bach'),
  w('The Four Seasons', 'Antonio Vivaldi'),
  w('Spring from The Four Seasons, RV 269', 'Antonio Vivaldi'),
  w('Summer from The Four Seasons, RV 315', 'Antonio Vivaldi'),
  w('Autumn from The Four Seasons, RV 293', 'Antonio Vivaldi'),
  w('Winter from The Four Seasons, RV 297', 'Antonio Vivaldi'),
  w('Violin Concerto No. 3 in G major, K. 216', 'W. A. Mozart'),
  w('Violin Concerto No. 4 in D major, K. 218', 'W. A. Mozart'),
  w('Violin Concerto No. 5 in A major, K. 219', 'W. A. Mozart'),
  w('Violin Concerto No. 1 in G minor, Op. 26', 'Max Bruch'),
  w('Scottish Fantasy, Op. 46', 'Max Bruch'),
  w('Violin Concerto in E minor, Op. 64', 'Felix Mendelssohn'),
  w('Violin Concerto in D major, Op. 61', 'Ludwig van Beethoven'),
  w('Violin Concerto in D major, Op. 77', 'Johannes Brahms'),
  w('Violin Concerto in D major, Op. 35', 'Pyotr Ilyich Tchaikovsky'),
  w('Violin Concerto in D minor, Op. 47', 'Jean Sibelius'),
  w('Violin Concerto No. 22 in A minor', 'Giovanni Battista Viotti'),
  w('Violin Concerto No. 9 in A minor, Op. 104', 'Charles-Auguste de Bériot'),
  w('Scène de ballet, Op. 100', 'Charles-Auguste de Bériot'),
  w('Violin Concerto No. 4 in D minor, Op. 31', 'Henri Vieuxtemps'),
  w('Violin Concerto No. 5 in A minor, Op. 37', 'Henri Vieuxtemps'),
  w('Violin Concerto No. 1 in D major, Op. 6', 'Niccolò Paganini'),
  w('Violin Concerto No. 2 in D minor, Op. 22', 'Henryk Wieniawski'),
  w('Symphonie espagnole, Op. 21', 'Édouard Lalo'),
  w('Violin Concerto No. 3 in B minor, Op. 61', 'Camille Saint-Saëns'),
  w('Introduction and Rondo Capriccioso, Op. 28', 'Camille Saint-Saëns'),
  w('Havanaise, Op. 83', 'Camille Saint-Saëns'),
  w('Violin Concerto in A minor, Op. 82', 'Alexander Glazunov'),
  w('Violin Concerto No. 1 in D major, Op. 19', 'Sergei Prokofiev'),
  w('Violin Concerto No. 2 in G minor, Op. 63', 'Sergei Prokofiev'),
  w('Violin Concerto, Op. 14', 'Samuel Barber'),
  w('Violin Concerto in D minor', 'Aram Khachaturian'),

  // Violin pieces and sonatas.
  w('Méditation from Thaïs', 'Jules Massenet'),
  w('Csárdás', 'Vittorio Monti'),
  w('Zigeunerweisen, Op. 20', 'Pablo de Sarasate'),
  w('Carmen Fantasy, Op. 25', 'Pablo de Sarasate'),
  w('Introduction and Tarantella, Op. 43', 'Pablo de Sarasate'),
  w('Liebesleid', 'Fritz Kreisler'),
  w('Liebesfreud', 'Fritz Kreisler'),
  w('Schön Rosmarin', 'Fritz Kreisler'),
  w('Praeludium and Allegro', 'Fritz Kreisler'),
  w('Tambourin chinois, Op. 3', 'Fritz Kreisler'),
  w("Salut d'amour, Op. 12", 'Edward Elgar'),
  w('Tzigane', 'Maurice Ravel'),
  w('Poème, Op. 25', 'Ernest Chausson'),
  w('Méditation, Op. 42 No. 1', 'Pyotr Ilyich Tchaikovsky'),
  w('Mélodie, Op. 42 No. 3', 'Pyotr Ilyich Tchaikovsky'),
  w('Valse-Scherzo, Op. 34', 'Pyotr Ilyich Tchaikovsky'),
  w('Romance No. 1 in G major, Op. 40', 'Ludwig van Beethoven'),
  w('Romance No. 2 in F major, Op. 50', 'Ludwig van Beethoven'),
  w('Violin Sonata No. 5 in F major, Op. 24 "Spring"', 'Ludwig van Beethoven'),
  w('Violin Sonata No. 9 in A major, Op. 47 "Kreutzer"', 'Ludwig van Beethoven'),
  w('Violin Sonata in E minor, K. 304', 'W. A. Mozart'),
  w('Violin Sonata No. 1 in G major, Op. 78', 'Johannes Brahms'),
  w('Violin Sonata in A major', 'César Franck'),
  w('Violin Sonata in D major, HWV 371', 'George Frideric Handel'),
  w('La Folia, Op. 5 No. 12', 'Arcangelo Corelli'),
  w("Devil's Trill Sonata", 'Giuseppe Tartini'),
  w('Romanian Folk Dances', 'Béla Bartók'),
  w('Hungarian Dance No. 5', 'Johannes Brahms'),
  w('Songs My Mother Taught Me, Op. 55 No. 4', 'Antonín Dvořák'),
  w('Air on the G String', 'J. S. Bach'),
  w('Ave Maria, D. 839', 'Franz Schubert'),
  w('Clair de lune', 'Claude Debussy'),
  w('Libertango', 'Astor Piazzolla'),
  w('Oblivion', 'Astor Piazzolla'),
  w("Theme from Schindler's List", 'John Williams'),

  // Viola.
  w('Viola Concerto in G major, TWV 51:G9', 'Georg Philipp Telemann'),
  w('Viola Concerto in D major, Op. 1', 'Carl Stamitz'),
  w('Viola Concerto in D major', 'Franz Anton Hoffmeister'),
  w('Viola Concerto in B minor', 'Henri Casadesus'),
  w('Sinfonia Concertante in E-flat major, K. 364', 'W. A. Mozart'),
  w('Viola Sonata No. 1 in F minor, Op. 120 No. 1', 'Johannes Brahms'),
  w('Viola Sonata No. 2 in E-flat major, Op. 120 No. 2', 'Johannes Brahms'),
  w('Märchenbilder, Op. 113', 'Robert Schumann'),
  w('Romance in F major, Op. 85', 'Max Bruch'),
  w('Viola Sonata in D minor', 'Mikhail Glinka'),
  w('Arpeggione Sonata in A minor, D. 821', 'Franz Schubert'),
  w('Viola Concerto', 'William Walton'),
  w('Viola Concerto', 'Béla Bartók'),
  w('Der Schwanendreher', 'Paul Hindemith'),

  // Cello.
  w('Cello Concerto No. 1 in C major, Hob. VIIb:1', 'Joseph Haydn'),
  w('Cello Concerto No. 2 in D major, Hob. VIIb:2', 'Joseph Haydn'),
  w('Cello Concerto in B-flat major, G. 482', 'Luigi Boccherini'),
  w('Cello Concerto No. 4 in G major, Op. 65', 'Georg Goltermann'),
  w('Cello Sonata in G major', 'Giovanni Battista Sammartini'),
  w('Cello Sonata No. 5 in E minor, RV 40', 'Antonio Vivaldi'),
  w('The Swan', 'Camille Saint-Saëns'),
  w('Cello Concerto No. 1 in A minor, Op. 33', 'Camille Saint-Saëns'),
  w('Cello Concerto in B minor, Op. 104', 'Antonín Dvořák'),
  w('Silent Woods, Op. 68 No. 5', 'Antonín Dvořák'),
  w('Cello Concerto in E minor, Op. 85', 'Edward Elgar'),
  w('Cello Concerto in A minor, Op. 129', 'Robert Schumann'),
  w('Variations on a Rococo Theme, Op. 33', 'Pyotr Ilyich Tchaikovsky'),
  w('Kol Nidrei, Op. 47', 'Max Bruch'),
  w('Élégie, Op. 24', 'Gabriel Fauré'),
  w('Après un rêve, Op. 7 No. 1', 'Gabriel Fauré'),
  w('Hungarian Rhapsody, Op. 68', 'David Popper'),
  w('Requiem, Op. 66', 'David Popper'),
  w('Tarantella, Op. 23', 'William Henry Squire'),
  w('Cello Sonata No. 3 in A major, Op. 69', 'Ludwig van Beethoven'),
  w('Cello Sonata No. 1 in E minor, Op. 38', 'Johannes Brahms'),
  w('Cello Sonata in D minor', 'Claude Debussy'),
  w('Cello Sonata in G minor, Op. 19', 'Sergei Rachmaninoff'),
  w('Vocalise, Op. 34 No. 14', 'Sergei Rachmaninoff'),
  w('Cello Sonata in D minor, Op. 40', 'Dmitri Shostakovich'),
  w('Cello Concerto No. 1 in E-flat major, Op. 107', 'Dmitri Shostakovich'),
  w('Cello Concerto No. 1 in G minor, Op. 49', 'Dmitri Kabalevsky'),
  w('Schelomo', 'Ernest Bloch'),

  // Double bass.
  w('Sonata in G minor', 'Henry Eccles'),
  w('The Elephant', 'Camille Saint-Saëns'),
  w('Double Bass Concerto in A major', 'Domenico Dragonetti'),
  w('Double Bass Concerto No. 2 in E major', 'Carl Ditters von Dittersdorf'),
  w('Double Bass Concerto in D major', 'Johann Baptist Vanhal'),
  w('Double Bass Concerto in F major', 'Antonio Capuzzi'),
  w('Double Bass Concerto No. 2 in B minor', 'Giovanni Bottesini'),
  w('Elegy in D', 'Giovanni Bottesini'),
  w('Tarantella', 'Giovanni Bottesini'),
  w('Gran Duo Concertante', 'Giovanni Bottesini'),
  w('Passione Amorosa', 'Giovanni Bottesini'),
  w('Double Bass Concerto in F-sharp minor, Op. 3', 'Serge Koussevitzky'),
  w('Chanson triste, Op. 2', 'Serge Koussevitzky'),
  w('Valse miniature, Op. 1 No. 2', 'Serge Koussevitzky'),
  w('Intermezzo and Tarantella, Op. 9', 'Reinhold Glière'),
  w('Prelude and Scherzo, Op. 32', 'Reinhold Glière'),
  w('Double Bass Sonata', 'Paul Hindemith'),
  w('Lieutenant Kijé Suite, Op. 60', 'Sergei Prokofiev'),

  // Orchestral, choral and chamber parts.
  w('Elijah, Op. 70', 'Felix Mendelssohn'),
  w('Messiah, HWV 56', 'George Frideric Handel'),
  w('Water Music', 'George Frideric Handel'),
  w('Canon in D', 'Johann Pachelbel'),
  w('Eine kleine Nachtmusik, K. 525', 'W. A. Mozart'),
  w('Divertimento in D major, K. 136', 'W. A. Mozart'),
  w('The Marriage of Figaro Overture, K. 492', 'W. A. Mozart'),
  w('Symphony No. 40 in G minor, K. 550', 'W. A. Mozart'),
  w('Symphony No. 41 in C major, K. 551 "Jupiter"', 'W. A. Mozart'),
  w('Symphony No. 35 in D major, K. 385 "Haffner"', 'W. A. Mozart'),
  w('Symphony No. 94 in G major "Surprise"', 'Joseph Haydn'),
  w('Symphony No. 5 in C minor, Op. 67', 'Ludwig van Beethoven'),
  w('Symphony No. 3 in E-flat major, Op. 55 "Eroica"', 'Ludwig van Beethoven'),
  w('Symphony No. 6 in F major, Op. 68 "Pastoral"', 'Ludwig van Beethoven'),
  w('Symphony No. 7 in A major, Op. 92', 'Ludwig van Beethoven'),
  w('Symphony No. 9 in D minor, Op. 125', 'Ludwig van Beethoven'),
  w('Symphony No. 8 in B minor, D. 759 "Unfinished"', 'Franz Schubert'),
  w('Symphony No. 9 in C major, D. 944 "Great"', 'Franz Schubert'),
  w('Symphony No. 4 in A major, Op. 90 "Italian"', 'Felix Mendelssohn'),
  w("A Midsummer Night's Dream, Op. 61", 'Felix Mendelssohn'),
  w('Symphony No. 1 in C minor, Op. 68', 'Johannes Brahms'),
  w('Symphony No. 2 in D major, Op. 73', 'Johannes Brahms'),
  w('Symphony No. 4 in E minor, Op. 98', 'Johannes Brahms'),
  w('Symphony No. 4 in F minor, Op. 36', 'Pyotr Ilyich Tchaikovsky'),
  w('Symphony No. 5 in E minor, Op. 64', 'Pyotr Ilyich Tchaikovsky'),
  w('Symphony No. 6 in B minor, Op. 74 "Pathétique"', 'Pyotr Ilyich Tchaikovsky'),
  w('Serenade for Strings in C major, Op. 48', 'Pyotr Ilyich Tchaikovsky'),
  w('The Nutcracker, Op. 71', 'Pyotr Ilyich Tchaikovsky'),
  w('Swan Lake, Op. 20', 'Pyotr Ilyich Tchaikovsky'),
  w('Symphony No. 9 in E minor, Op. 95 "From the New World"', 'Antonín Dvořák'),
  w('Serenade for Strings in E major, Op. 22', 'Antonín Dvořák'),
  w('String Quartet No. 12 in F major, Op. 96 "American"', 'Antonín Dvořák'),
  w('Serenade for Strings in E minor, Op. 20', 'Edward Elgar'),
  w('Enigma Variations, Op. 36', 'Edward Elgar'),
  w('Holberg Suite, Op. 40', 'Edvard Grieg'),
  w('Peer Gynt Suite No. 1, Op. 46', 'Edvard Grieg'),
  w('Adagio for Strings, Op. 11', 'Samuel Barber'),
  w('Simple Symphony, Op. 4', 'Benjamin Britten'),
  w("St Paul's Suite, Op. 29 No. 2", 'Gustav Holst'),
  w('The Planets, Op. 32', 'Gustav Holst'),
  w('Fantasia on a Theme by Thomas Tallis', 'Ralph Vaughan Williams'),
  w('Symphony No. 2 in D major, Op. 43', 'Jean Sibelius'),
  w('Finlandia, Op. 26', 'Jean Sibelius'),
  w('Symphony No. 1 in D major', 'Gustav Mahler'),
  w('Symphony No. 5 in D minor, Op. 47', 'Dmitri Shostakovich'),
  w('String Quartet No. 8 in C minor, Op. 110', 'Dmitri Shostakovich'),
  w('Romeo and Juliet, Op. 64', 'Sergei Prokofiev'),
  w('Brandenburg Concerto No. 3 in G major, BWV 1048', 'J. S. Bach'),
  w('Brandenburg Concerto No. 5 in D major, BWV 1050', 'J. S. Bach'),
  w('Orchestral Suite No. 3 in D major, BWV 1068', 'J. S. Bach'),
  w('Gloria, RV 589', 'Antonio Vivaldi'),
  w('Christmas Concerto, Op. 6 No. 8', 'Arcangelo Corelli'),
  w('Adagio in G minor', 'Tomaso Albinoni'),
  w('Trout Quintet, D. 667', 'Franz Schubert'),
  w('Death and the Maiden, D. 810', 'Franz Schubert'),
  w('String Quartet in C major, Op. 76 No. 3 "Emperor"', 'Joseph Haydn'),
  w('String Quartet in G minor, Op. 10', 'Claude Debussy'),
  w('String Quartet in F major', 'Maurice Ravel'),
  w('Boléro', 'Maurice Ravel'),
  w('Danse macabre, Op. 40', 'Camille Saint-Saëns'),
  w('The Carnival of the Animals', 'Camille Saint-Saëns'),
  w('Carmen', 'Georges Bizet'),
  w('William Tell Overture', 'Gioachino Rossini'),
  w('Polovtsian Dances', 'Alexander Borodin'),
  w('Scheherazade, Op. 35', 'Nikolai Rimsky-Korsakov'),
  w('Pictures at an Exhibition', 'Modest Mussorgsky'),
  w('The Moldau', 'Bedřich Smetana'),
  w('The Firebird', 'Igor Stravinsky'),
  w('The Rite of Spring', 'Igor Stravinsky'),
  w('Ein Heldenleben, Op. 40', 'Richard Strauss'),
  w('Don Juan, Op. 20', 'Richard Strauss'),
  w('Otello', 'Giuseppe Verdi'),
];
